version: '3.8'

services:

  api-ccw:
    container_name: api-ccw
    build:
      context: ./
      cache_from:
        - ccw:nx-base
      dockerfile: ./apps/api/Dockerfile
    image: api:dev
    ports:
      - 3010:3000
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      CORS_ENV: '*'
    restart: on-failure
