export enum Role {
    ADMIN,
    MODERATOR,
    VIEWER,

    ORGANIZATION_ADMIN,
    ORGANIZATION_MODERATOR,
    ORGANIZATION_VIEWER,

    COMMUNITY_ADMIN,
    COMMUNITY_MODERATOR,
    COMMUNITY_VIEWER,
  }